version: "3.7"

services:

  #Camunda Database
  postgres-db:
    container_name: postgres-db
    image: postgres:${DB_POSTGRES_VERSION}
    command: postgres -c 'max_connections=200'
    volumes:
      - .././db/pgdata-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
    healthcheck:    
      test: "exit 0"
    ports:
      - "5437:5432"  
    networks:
      - stack1-network
      
volumes:
  pgdata-db:
  

networks:
  stack1-network:
    driver: bridge  
    
    
 