spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5437/testes
    username: dbtestesadmin
    password: dbtestespassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true